image: maven:3.6.1-jdk-8

stages:
  - build

pages:
  tags:
    - asprunner
  stage: build
  script:
    - mvn
    - mv target/generated-docs public
    - cp -R api public/
  artifacts:
    paths:
      - public
  only:
    - master





