= LinkedFactory: Industrial Digital Twins

== What is LinkedFactory?

LinkedFactory defines *APIs* and a *JSON-based data format* for managing time series data about assets to create connected digital representations of technical systems.

The core components can be augmented with *RDF-based descriptions* for
representing *metadata* like the structure, components or attributes of
assets as well as other provenance information of time series data.
In this context *SPARQL* can be used to execute queries against time series data and the related metadata.

== Components

LinkedFactory is based on the following standards and components:

*Core components:*

* xref:timeseries:api.adoc[*API*] for storing and retrieving time series data
* flexible xref:timeseries:json.adoc[*JSON-based format*] for exchanging data

*Optional components for metadata:*

* https://www.w3.org/TR/rdf11-concepts/[*RDF*] for metadata of assets with associated properties and relationships
  to other assets.
* http://www.w3.org/TR/sparql11-http-rdf-update/[*Graph Store HTTP Protocol*] as simple HTTP-based protocol for modifiying the RDF data about assets
* https://www.w3.org/TR/sparql11-query/[*SPARQL interface*] for complex queries against RDF and time series data

== Graph store

The endpoint `/models` provides an interface according to the https://www.w3.org/TR/sparql11-http-rdf-update/[SPARQL 1.1 Graph Store HTTP Protocol]. 

IMPORTANT: The only difference is that the platform uses the parameter `model` instead of `graph` to specify the target named graph.

== SPARQL interface

The endpoint `/sparql` provides an interface according to https://www.w3.org/TR/sparql11-overview/[SPARQL 1.1].

NOTE: The parameter *model* must be used to specify  the target model for the query. The *default model* for LinkedFactory data is `http://linkedfactory.iwu.fraunhofer.de/data/`.


[subs=+quotes]
[source,sparql]
----
select ?property ?value ?time {
  service *<kvin:>* { 
    <http://example.org/resource1> 
       ?property [ *<kvin:value>* ?value; *<kvin:time>* ?time ; <kvin:limit> 1 ] . 
  }
} order by ?time
----

== Grafana Datasource

A Grafana Datasource for the LinkedFactory API is available at https://github.com/linkedfactory/linkedfactory-grafana-ds
