= LinkedFactory: Industrial Knowledge Graph

== What is LinkedFactory?

LinkedFactory is a set of APIs for combining RDF and time series data to create digital representations of technical systems.

== Components

LinkedFactory is based on the following standards and components:

* https://www.w3.org/TR/rdf11-concepts/[*RDF*] is used as a flexible format to describe any kind of asset with associated properties and relationships
  to other assets.
* http://www.w3.org/TR/sparql11-http-rdf-update/[*Graph Store HTTP Protocol*] is a simple HTTP-based protocol for modifiying the RDF data about assets
* xref:timeseries:api.adoc[*API*] for storing and retrieving time series data
* https://www.w3.org/TR/sparql11-query/[*SPARQL interface*] for complex queries against RDF and time series data

== Graph store

The endpoint `/models` provides an interface according to the https://www.w3.org/TR/sparql11-http-rdf-update/[SPARQL 1.1 Graph Store HTTP Protocol]. 

IMPORTANT: The only difference is that the platform uses the parameter `model` instead of `graph` to specify the target named graph.

== SPARQL interface

The endpoint `/sparql` provides an interface according to https://www.w3.org/TR/sparql11-overview/[SPARQL 1.1].

NOTE: The parameter *model* must be used to specify  the target model for the query. The *default model* for LinkedFactory data is `http://linkedfactory.iwu.fraunhofer.de/data/`.


[subs=+quotes]
[source,sparql]
----
select ?property ?value ?time {
  service *<kvin:>* { 
    <http://example.org/resource1> 
       ?property [ *<kvin:value>* ?value; *<kvin:time>* ?time ; <kvin:limit> 1 ] . 
  }
} order by ?time
----

== Grafana connector

TBD